#!/bin/sh
cd ../
rm gradle/verification-metadata.xml
cp scripts/verification-metadata-template.xml gradle/verification-metadata.xml
./gradlew --no-daemon --refresh-dependencies --write-verification-metadata sha256 assemble
