name: Docker image release for latest tags from git tag

on:
  push:
    tags:
      - '*'

# Declare default permissions as read only.
permissions: read-all

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 #v6.1.0
        with:
          images: rsksmart/rskj
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            # This is used for generating IRIS-3 out of IRIS-3.x.y.
            type=match,pattern=(\w+-\d+)\.\d+\.\d+.*,group=1

      - name: DockerHub login
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to registry
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf #v7.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
